# Generated by Django 2.2.3 on 2020-03-09 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cms_Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_slider', models.ImageField(blank=True, null=True, upload_to='imgs/img_slider', verbose_name='Imagem Slider')),
                ('descricao', models.TextField(verbose_name='Descrição da Imagem')),
                ('cms', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Cms.Cms')),
            ],
        ),
    ]
