# Generated by Django 2.2.3 on 2020-03-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0002_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenda',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Administrador'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='is_gerente',
            field=models.BooleanField(default=False, verbose_name='Gerente de Marca'),
        ),
    ]
