# Generated by Django 2.2.3 on 2020-03-09 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cliente', '0003_auto_20200309_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenda_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Gerente de Marca')),
                ('revenda', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Cliente.Revenda', verbose_name='Revenda')),
                ('user_revenda', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
