# Generated by Django 2.2.3 on 2020-03-11 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0005_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Cliente.Empresa', verbose_name='Empresa'),
        ),
    ]
