# Generated by Django 2.2.3 on 2020-03-05 19:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pn', models.CharField(max_length=150, verbose_name='Part Number')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('is_acessorio', models.BooleanField(default=False)),
                ('date_entered', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Entrada')),
            ],
        ),
        migrations.CreateModel(
            name='Equip_Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('qty', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('id_equip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Equipamento.Equipamento', verbose_name='Equipamento')),
                ('id_projeto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Registro.Projeto', verbose_name='Projeto')),
            ],
        ),
    ]
