# Generated by Django 2.2.3 on 2020-03-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equip_projeto',
            name='name',
            field=models.CharField(default='Equip', max_length=150),
        ),
    ]
