# Generated by Django 2.2.3 on 2020-03-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipamento', '0002_equip_projeto_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='is_acessorio',
            field=models.BooleanField(default=False, verbose_name='Acessório'),
        ),
    ]
