# Generated by Django 2.2.3 on 2020-03-05 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cliente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicacao', models.TextField(verbose_name='Aplicação')),
                ('esp_tec', models.TextField(verbose_name='Especificações Técnicas')),
                ('homologa', models.BooleanField(default=False, verbose_name='Homologado')),
                ('colet_dados', models.TextField(default=False, verbose_name='Coletor de dados')),
                ('parc_soft', models.CharField(default=False, max_length=255, verbose_name='Parceiro de software')),
                ('date_concl', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Conclusão')),
                ('info_ad', models.TextField(verbose_name='Informações adicionais')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entered', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de entrada')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Cliente.Cliente_Final', verbose_name='Cliente Final')),
                ('id_projeto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Registro.Projeto', verbose_name='Projeto')),
                ('id_revenda', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Cliente.Revenda', verbose_name='Revenda')),
                ('id_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
        ),
    ]
