# Generated by Django 2.2.3 on 2020-03-05 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0002_auto_20200305_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='id_vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Cliente.Vendedor', verbose_name='Vendedor'),
        ),
    ]
