# Generated by Django 2.2.3 on 2020-03-16 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0010_auto_20200316_0932'),
        ('Registro', '0005_registro_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='id_revenda_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Cliente.Revenda_User', verbose_name='Revenda Usuário'),
        ),
    ]
