# Generated by Django 2.2.3 on 2020-03-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0007_auto_20200316_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
    ]
