# Generated by Django 2.2.3 on 2020-03-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0008_registro_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='atualizado',
            field=models.BooleanField(default=False, verbose_name='Atualizado'),
        ),
        migrations.AddField(
            model_name='registro',
            name='date_atualizado',
            field=models.DateField(blank=True, null=True, verbose_name='Data Atualização'),
        ),
    ]
