# Generated by Django 2.2.3 on 2020-03-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0011_registro_numero_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='marca',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Marca'),
        ),
    ]
