# Generated by Django 2.2.3 on 2020-03-05 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=255, verbose_name='CNPJ')),
                ('rua', models.CharField(max_length=255, verbose_name='Rua')),
                ('cidade', models.CharField(max_length=255, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=255, verbose_name='Estado')),
                ('contato', models.CharField(max_length=255, verbose_name='Contato')),
                ('telefone', models.CharField(max_length=255, verbose_name='Telefone')),
                ('date_entered', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de entrada')),
                ('user_revenda', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente_Final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=255, verbose_name='CNPJ')),
                ('rua', models.CharField(max_length=255, verbose_name='Rua')),
                ('cidade', models.CharField(max_length=255, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=255, verbose_name='Estado')),
                ('contato', models.CharField(max_length=255, verbose_name='Contato')),
                ('telefone', models.CharField(max_length=255, verbose_name='Telefone')),
                ('date_entered', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de entrada')),
                ('user_revenda', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
