# Generated by Django 2.2.3 on 2020-03-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0007_remove_revenda_user_revenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente_final',
            name='user_revenda',
        ),
        migrations.RemoveField(
            model_name='revenda',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='revenda_user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Administrador'),
        ),
    ]
