# Generated by Django 2.2.3 on 2020-03-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0008_auto_20200311_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente_final',
            name='contato',
        ),
        migrations.AddField(
            model_name='cliente_final',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='E-mail'),
        ),
    ]
