# Generated by Django 2.2.3 on 2020-03-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='colet_dados',
            field=models.TextField(verbose_name='Coletor de dados'),
        ),
    ]
