# Generated by Django 2.2.3 on 2020-03-16 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0006_registro_id_revenda_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='id_revenda_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cliente.Revenda_User', verbose_name='Revenda Usuário'),
        ),
    ]
