# Generated by Django 2.2.3 on 2020-03-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0009_auto_20200316_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='name',
            field=models.CharField(default='Registro Oportunidade', max_length=150, verbose_name='name'),
        ),
    ]
