# Generated by Django 2.2.3 on 2020-03-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0010_registro_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='numero_registro',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Número de Registro'),
        ),
    ]
